[package]
name = "zmqpub"
version = "0.1.0"
edition = "2024"

[dependencies]
zmq = "0.10.0"
chrono = "0.4.41"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
clap = { version = "4.5.39", features = ["derive"] }
